require 'rubygems'
Gem::manage_gems
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
    s.platform  =   Gem::Platform::RUBY
    s.name      =   "WiKID"
    s.version   =   "@VERSION@"
    s.author    =   "Greg Haygood"
    s.email     =   "ghaygood @nospam@ wikidsystems(dot)com"
		s.homepage	= 	"http://sourceforge.net/projects/wikid-twofactor"
		s.rubyforge_project	= 	"wikid"
    s.summary   =   "A network client module for the WiKID Strong Authentication system"
    s.files     =   FileList['lib/*.rb', 'doc/*', 'share/*', 'test/*'].to_a
    s.require_path  =   "lib"
    s.test_files = Dir.glob('tests/*.rb')
    s.has_rdoc  =   true
    s.extra_rdoc_files  =   ["doc/README"]

#	s.add_dependency("rexml")
end

Rake::GemPackageTask.new(spec) do |pkg|
    pkg.need_tar = true
end

task :default => "pkg/#{spec.name}-#{spec.version}.gem" do
    puts "generated latest version"
end
